version: '2'
services:
  nats:
    image: nats-streaming
    expose:
      - "4222"
    ports:
      - "8222:8222"
      - "4222:4222"
    hostname: nats-server
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    hostname: mongodb-server