// Code generated by go-swagger; DO NOT EDIT.

package kardex

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetKardexByIDHandlerFunc turns a function with the right signature into a get kardex by Id handler
type GetKardexByIDHandlerFunc func(GetKardexByIDParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetKardexByIDHandlerFunc) Handle(params GetKardexByIDParams) middleware.Responder {
	return fn(params)
}

// GetKardexByIDHandler interface for that can handle valid get kardex by Id params
type GetKardexByIDHandler interface {
	Handle(GetKardexByIDParams) middleware.Responder
}

// NewGetKardexByID creates a new http.Handler for the get kardex by Id operation
func NewGetKardexByID(ctx *middleware.Context, handler GetKardexByIDHandler) *GetKardexByID {
	return &GetKardexByID{Context: ctx, Handler: handler}
}

/*GetKardexByID swagger:route GET /inventory/kardex/{kardexId} kardex getKardexById

Fin kardex by ID

Returns a single kardex

*/
type GetKardexByID struct {
	Context *middleware.Context
	Handler GetKardexByIDHandler
}

func (o *GetKardexByID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetKardexByIDParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
