// Code generated by go-swagger; DO NOT EDIT.

package kardex

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// RegisterKardexCreatedCode is the HTTP code returned for type RegisterKardexCreated
const RegisterKardexCreatedCode int = 201

/*RegisterKardexCreated Submitted kardex registration

swagger:response registerKardexCreated
*/
type RegisterKardexCreated struct {
}

// NewRegisterKardexCreated creates RegisterKardexCreated with default headers values
func NewRegisterKardexCreated() *RegisterKardexCreated {

	return &RegisterKardexCreated{}
}

// WriteResponse to the client
func (o *RegisterKardexCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(201)
}

// RegisterKardexMethodNotAllowedCode is the HTTP code returned for type RegisterKardexMethodNotAllowed
const RegisterKardexMethodNotAllowedCode int = 405

/*RegisterKardexMethodNotAllowed Invalid input

swagger:response registerKardexMethodNotAllowed
*/
type RegisterKardexMethodNotAllowed struct {
}

// NewRegisterKardexMethodNotAllowed creates RegisterKardexMethodNotAllowed with default headers values
func NewRegisterKardexMethodNotAllowed() *RegisterKardexMethodNotAllowed {

	return &RegisterKardexMethodNotAllowed{}
}

// WriteResponse to the client
func (o *RegisterKardexMethodNotAllowed) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(405)
}
