// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// Purchase Purchase
// swagger:model Purchase
type Purchase struct {

	// product Id
	// Required: true
	ProductID *int64 `json:"productId"`

	// quantity
	// Required: true
	Quantity *int64 `json:"quantity"`

	// unit price
	// Required: true
	UnitPrice *float64 `json:"unitPrice"`
}

// Validate validates this purchase
func (m *Purchase) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateProductID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateQuantity(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateUnitPrice(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Purchase) validateProductID(formats strfmt.Registry) error {

	if err := validate.Required("productId", "body", m.ProductID); err != nil {
		return err
	}

	return nil
}

func (m *Purchase) validateQuantity(formats strfmt.Registry) error {

	if err := validate.Required("quantity", "body", m.Quantity); err != nil {
		return err
	}

	return nil
}

func (m *Purchase) validateUnitPrice(formats strfmt.Registry) error {

	if err := validate.Required("unitPrice", "body", m.UnitPrice); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *Purchase) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Purchase) UnmarshalBinary(b []byte) error {
	var res Purchase
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
