// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ReturnSale ReturnSale
// swagger:model ReturnSale
type ReturnSale struct {

	// quantity
	// Required: true
	Quantity *int64 `json:"quantity"`

	// sale Id
	// Required: true
	SaleID *int64 `json:"saleId"`
}

// Validate validates this return sale
func (m *ReturnSale) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateQuantity(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSaleID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ReturnSale) validateQuantity(formats strfmt.Registry) error {

	if err := validate.Required("quantity", "body", m.Quantity); err != nil {
		return err
	}

	return nil
}

func (m *ReturnSale) validateSaleID(formats strfmt.Registry) error {

	if err := validate.Required("saleId", "body", m.SaleID); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ReturnSale) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ReturnSale) UnmarshalBinary(b []byte) error {
	var res ReturnSale
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
