// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ReturnPurchase ReturnPurchase
// swagger:model ReturnPurchase
type ReturnPurchase struct {

	// purchase Id
	// Required: true
	PurchaseID *int64 `json:"purchaseId"`

	// quantity
	// Required: true
	Quantity *int64 `json:"quantity"`
}

// Validate validates this return purchase
func (m *ReturnPurchase) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validatePurchaseID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateQuantity(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ReturnPurchase) validatePurchaseID(formats strfmt.Registry) error {

	if err := validate.Required("purchaseId", "body", m.PurchaseID); err != nil {
		return err
	}

	return nil
}

func (m *ReturnPurchase) validateQuantity(formats strfmt.Registry) error {

	if err := validate.Required("quantity", "body", m.Quantity); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ReturnPurchase) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ReturnPurchase) UnmarshalBinary(b []byte) error {
	var res ReturnPurchase
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
