// Code generated by go-swagger; DO NOT EDIT.

package purchase

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// PlacePurchaseCreatedCode is the HTTP code returned for type PlacePurchaseCreated
const PlacePurchaseCreatedCode int = 201

/*PlacePurchaseCreated Created

swagger:response placePurchaseCreated
*/
type PlacePurchaseCreated struct {
}

// NewPlacePurchaseCreated creates PlacePurchaseCreated with default headers values
func NewPlacePurchaseCreated() *PlacePurchaseCreated {

	return &PlacePurchaseCreated{}
}

// WriteResponse to the client
func (o *PlacePurchaseCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(201)
}

// PlacePurchaseBadRequestCode is the HTTP code returned for type PlacePurchaseBadRequest
const PlacePurchaseBadRequestCode int = 400

/*PlacePurchaseBadRequest Invalid Order

swagger:response placePurchaseBadRequest
*/
type PlacePurchaseBadRequest struct {
}

// NewPlacePurchaseBadRequest creates PlacePurchaseBadRequest with default headers values
func NewPlacePurchaseBadRequest() *PlacePurchaseBadRequest {

	return &PlacePurchaseBadRequest{}
}

// WriteResponse to the client
func (o *PlacePurchaseBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}
