// Code generated by go-swagger; DO NOT EDIT.

package purchase

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// ReturnPurchaseCreatedCode is the HTTP code returned for type ReturnPurchaseCreated
const ReturnPurchaseCreatedCode int = 201

/*ReturnPurchaseCreated Created

swagger:response returnPurchaseCreated
*/
type ReturnPurchaseCreated struct {
}

// NewReturnPurchaseCreated creates ReturnPurchaseCreated with default headers values
func NewReturnPurchaseCreated() *ReturnPurchaseCreated {

	return &ReturnPurchaseCreated{}
}

// WriteResponse to the client
func (o *ReturnPurchaseCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(201)
}

// ReturnPurchaseBadRequestCode is the HTTP code returned for type ReturnPurchaseBadRequest
const ReturnPurchaseBadRequestCode int = 400

/*ReturnPurchaseBadRequest Invalid Order

swagger:response returnPurchaseBadRequest
*/
type ReturnPurchaseBadRequest struct {
}

// NewReturnPurchaseBadRequest creates ReturnPurchaseBadRequest with default headers values
func NewReturnPurchaseBadRequest() *ReturnPurchaseBadRequest {

	return &ReturnPurchaseBadRequest{}
}

// WriteResponse to the client
func (o *ReturnPurchaseBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}
