// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protobuf/kardex.proto

package protobuf

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RegisterKardexCommand struct {
	KardexId             string   `protobuf:"bytes,1,opt,name=kardex_id,json=kardexId,proto3" json:"kardex_id,omitempty"`
	ProductId            string   `protobuf:"bytes,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	CreatedOn            int64    `protobuf:"varint,3,opt,name=created_on,json=createdOn,proto3" json:"created_on,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterKardexCommand) Reset()         { *m = RegisterKardexCommand{} }
func (m *RegisterKardexCommand) String() string { return proto.CompactTextString(m) }
func (*RegisterKardexCommand) ProtoMessage()    {}
func (*RegisterKardexCommand) Descriptor() ([]byte, []int) {
	return fileDescriptor_e67e05e85ac16113, []int{0}
}

func (m *RegisterKardexCommand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterKardexCommand.Unmarshal(m, b)
}
func (m *RegisterKardexCommand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterKardexCommand.Marshal(b, m, deterministic)
}
func (m *RegisterKardexCommand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterKardexCommand.Merge(m, src)
}
func (m *RegisterKardexCommand) XXX_Size() int {
	return xxx_messageInfo_RegisterKardexCommand.Size(m)
}
func (m *RegisterKardexCommand) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterKardexCommand.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterKardexCommand proto.InternalMessageInfo

func (m *RegisterKardexCommand) GetKardexId() string {
	if m != nil {
		return m.KardexId
	}
	return ""
}

func (m *RegisterKardexCommand) GetProductId() string {
	if m != nil {
		return m.ProductId
	}
	return ""
}

func (m *RegisterKardexCommand) GetCreatedOn() int64 {
	if m != nil {
		return m.CreatedOn
	}
	return 0
}

func init() {
	proto.RegisterType((*RegisterKardexCommand)(nil), "protobuf.RegisterKardexCommand")
}

func init() { proto.RegisterFile("protobuf/kardex.proto", fileDescriptor_e67e05e85ac16113) }

var fileDescriptor_e67e05e85ac16113 = []byte{
	// 138 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2d, 0x28, 0xca, 0x2f,
	0xc9, 0x4f, 0x2a, 0x4d, 0xd3, 0xcf, 0x4e, 0x2c, 0x4a, 0x49, 0xad, 0xd0, 0x03, 0xf3, 0x85, 0x38,
	0x60, 0xc2, 0x4a, 0x45, 0x5c, 0xa2, 0x41, 0xa9, 0xe9, 0x99, 0xc5, 0x25, 0xa9, 0x45, 0xde, 0x60,
	0x15, 0xce, 0xf9, 0xb9, 0xb9, 0x89, 0x79, 0x29, 0x42, 0xd2, 0x5c, 0x9c, 0x10, 0x2d, 0xf1, 0x99,
	0x29, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x1c, 0x10, 0x01, 0xcf, 0x14, 0x21, 0x59, 0x2e,
	0xae, 0x82, 0xa2, 0xfc, 0x94, 0xd2, 0xe4, 0x12, 0x90, 0x2c, 0x13, 0x58, 0x96, 0x13, 0x2a, 0x02,
	0x91, 0x4e, 0x2e, 0x4a, 0x4d, 0x2c, 0x49, 0x4d, 0x89, 0xcf, 0xcf, 0x93, 0x60, 0x56, 0x60, 0xd4,
	0x60, 0x0e, 0xe2, 0x84, 0x8a, 0xf8, 0xe7, 0x25, 0xb1, 0x81, 0x6d, 0x37, 0x06, 0x04, 0x00, 0x00,
	0xff, 0xff, 0x57, 0xf8, 0x80, 0xbe, 0x9d, 0x00, 0x00, 0x00,
}
