// Code generated by go-swagger; DO NOT EDIT.

package sale

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// PlaceSaleCreatedCode is the HTTP code returned for type PlaceSaleCreated
const PlaceSaleCreatedCode int = 201

/*PlaceSaleCreated Created

swagger:response placeSaleCreated
*/
type PlaceSaleCreated struct {
}

// NewPlaceSaleCreated creates PlaceSaleCreated with default headers values
func NewPlaceSaleCreated() *PlaceSaleCreated {

	return &PlaceSaleCreated{}
}

// WriteResponse to the client
func (o *PlaceSaleCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(201)
}

// PlaceSaleBadRequestCode is the HTTP code returned for type PlaceSaleBadRequest
const PlaceSaleBadRequestCode int = 400

/*PlaceSaleBadRequest Invalid Order

swagger:response placeSaleBadRequest
*/
type PlaceSaleBadRequest struct {
}

// NewPlaceSaleBadRequest creates PlaceSaleBadRequest with default headers values
func NewPlaceSaleBadRequest() *PlaceSaleBadRequest {

	return &PlaceSaleBadRequest{}
}

// WriteResponse to the client
func (o *PlaceSaleBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}
