// Code generated by go-swagger; DO NOT EDIT.

package sale

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// PlaceSaleHandlerFunc turns a function with the right signature into a place sale handler
type PlaceSaleHandlerFunc func(PlaceSaleParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PlaceSaleHandlerFunc) Handle(params PlaceSaleParams) middleware.Responder {
	return fn(params)
}

// PlaceSaleHandler interface for that can handle valid place sale params
type PlaceSaleHandler interface {
	Handle(PlaceSaleParams) middleware.Responder
}

// NewPlaceSale creates a new http.Handler for the place sale operation
func NewPlaceSale(ctx *middleware.Context, handler PlaceSaleHandler) *PlaceSale {
	return &PlaceSale{Context: ctx, Handler: handler}
}

/*PlaceSale swagger:route POST /inventory/sale sale placeSale

Place a sale

*/
type PlaceSale struct {
	Context *middleware.Context
	Handler PlaceSaleHandler
}

func (o *PlaceSale) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPlaceSaleParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
