// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "This is a simple API",
    "title": "Simple Kardex API",
    "contact": {
      "email": "337n4nd0@gmail.com"
    },
    "license": {
      "name": "Apache 2.0",
      "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
    },
    "version": "1.0.0"
  },
  "host": "localhost:3030",
  "basePath": "/f3rn4nd0/chikitania/1.0.0",
  "paths": {
    "/inventory/kardex": {
      "post": {
        "description": "Register a new kardex to the inventory",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "kardex"
        ],
        "summary": "Register a new kardex",
        "operationId": "registerKardex",
        "parameters": [
          {
            "description": "Kardex object that needs to be registered to the inventory",
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/NewKardex"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Submitted kardex registration"
          },
          "405": {
            "description": "Invalid input"
          }
        }
      }
    },
    "/inventory/kardex/{kardexId}": {
      "get": {
        "description": "Returns a single kardex",
        "produces": [
          "application/json"
        ],
        "tags": [
          "kardex"
        ],
        "summary": "Fin kardex by ID",
        "operationId": "getKardexById",
        "parameters": [
          {
            "type": "string",
            "description": "ID of kardex to return",
            "name": "kardexId",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Successful operation",
            "schema": {
              "$ref": "#/definitions/Kardex"
            }
          },
          "400": {
            "description": "Invalid ID supplied"
          },
          "404": {
            "description": "Kardex not found"
          }
        }
      }
    },
    "/inventory/purchase": {
      "post": {
        "produces": [
          "application/json"
        ],
        "tags": [
          "purchase"
        ],
        "summary": "Place a purchase",
        "operationId": "placePurchase",
        "parameters": [
          {
            "description": "placed a purchase for a product",
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Purchase"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Created"
          },
          "400": {
            "description": "Invalid Order"
          }
        }
      }
    },
    "/inventory/purchase/return": {
      "post": {
        "produces": [
          "application/json"
        ],
        "tags": [
          "purchase"
        ],
        "summary": "Return on purchase",
        "operationId": "returnPurchase",
        "parameters": [
          {
            "description": "placed a return on purchase",
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/ReturnPurchase"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Created"
          },
          "400": {
            "description": "Invalid Order"
          }
        }
      }
    },
    "/inventory/sale": {
      "post": {
        "produces": [
          "application/json"
        ],
        "tags": [
          "sale"
        ],
        "summary": "Place a sale",
        "operationId": "placeSale",
        "parameters": [
          {
            "description": "placed a sale for a product",
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Sale"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Created"
          },
          "400": {
            "description": "Invalid Order"
          }
        }
      }
    },
    "/inventory/sale/return": {
      "post": {
        "produces": [
          "application/json"
        ],
        "tags": [
          "sale"
        ],
        "summary": "Return on sale",
        "operationId": "returnSale",
        "parameters": [
          {
            "description": "placed a return on sale",
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/ReturnSale"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Created"
          },
          "400": {
            "description": "Invalid Order"
          }
        }
      }
    }
  },
  "definitions": {
    "Kardex": {
      "type": "object",
      "title": "Kardex",
      "properties": {
        "id": {
          "type": "string"
        },
        "productId": {
          "type": "string"
        }
      }
    },
    "NewKardex": {
      "type": "object",
      "title": "Kardex",
      "properties": {
        "productId": {
          "type": "string"
        }
      }
    },
    "Purchase": {
      "type": "object",
      "title": "Purchase",
      "required": [
        "productId",
        "quantity",
        "unitPrice"
      ],
      "properties": {
        "productId": {
          "type": "integer",
          "format": "int64"
        },
        "quantity": {
          "type": "integer",
          "format": "int64"
        },
        "unitPrice": {
          "type": "number",
          "format": "double",
          "example": 0.5
        }
      }
    },
    "ReturnPurchase": {
      "type": "object",
      "title": "ReturnPurchase",
      "required": [
        "purchaseId",
        "quantity"
      ],
      "properties": {
        "purchaseId": {
          "type": "integer",
          "format": "int64"
        },
        "quantity": {
          "type": "integer",
          "format": "int64"
        }
      }
    },
    "ReturnSale": {
      "type": "object",
      "title": "ReturnSale",
      "required": [
        "quantity",
        "saleId"
      ],
      "properties": {
        "quantity": {
          "type": "integer",
          "format": "int64"
        },
        "saleId": {
          "type": "integer",
          "format": "int64"
        }
      }
    },
    "Sale": {
      "type": "object",
      "title": "Sale",
      "required": [
        "productId",
        "quantity"
      ],
      "properties": {
        "productId": {
          "type": "integer",
          "format": "int64"
        },
        "quantity": {
          "type": "integer",
          "format": "int64"
        }
      }
    }
  },
  "tags": [
    {
      "description": "Tool that allows you to summarize information about your company's inventory transactions",
      "name": "kardex"
    },
    {
      "description": "Record the purchases of inventory items",
      "name": "purchase"
    },
    {
      "description": "Record the sale of inventory items",
      "name": "sale"
    }
  ]
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "This is a simple API",
    "title": "Simple Kardex API",
    "contact": {
      "email": "337n4nd0@gmail.com"
    },
    "license": {
      "name": "Apache 2.0",
      "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
    },
    "version": "1.0.0"
  },
  "host": "localhost:3030",
  "basePath": "/f3rn4nd0/chikitania/1.0.0",
  "paths": {
    "/inventory/kardex": {
      "post": {
        "description": "Register a new kardex to the inventory",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "kardex"
        ],
        "summary": "Register a new kardex",
        "operationId": "registerKardex",
        "parameters": [
          {
            "description": "Kardex object that needs to be registered to the inventory",
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/NewKardex"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Submitted kardex registration"
          },
          "405": {
            "description": "Invalid input"
          }
        }
      }
    },
    "/inventory/kardex/{kardexId}": {
      "get": {
        "description": "Returns a single kardex",
        "produces": [
          "application/json"
        ],
        "tags": [
          "kardex"
        ],
        "summary": "Fin kardex by ID",
        "operationId": "getKardexById",
        "parameters": [
          {
            "type": "string",
            "description": "ID of kardex to return",
            "name": "kardexId",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Successful operation",
            "schema": {
              "$ref": "#/definitions/Kardex"
            }
          },
          "400": {
            "description": "Invalid ID supplied"
          },
          "404": {
            "description": "Kardex not found"
          }
        }
      }
    },
    "/inventory/purchase": {
      "post": {
        "produces": [
          "application/json"
        ],
        "tags": [
          "purchase"
        ],
        "summary": "Place a purchase",
        "operationId": "placePurchase",
        "parameters": [
          {
            "description": "placed a purchase for a product",
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Purchase"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Created"
          },
          "400": {
            "description": "Invalid Order"
          }
        }
      }
    },
    "/inventory/purchase/return": {
      "post": {
        "produces": [
          "application/json"
        ],
        "tags": [
          "purchase"
        ],
        "summary": "Return on purchase",
        "operationId": "returnPurchase",
        "parameters": [
          {
            "description": "placed a return on purchase",
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/ReturnPurchase"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Created"
          },
          "400": {
            "description": "Invalid Order"
          }
        }
      }
    },
    "/inventory/sale": {
      "post": {
        "produces": [
          "application/json"
        ],
        "tags": [
          "sale"
        ],
        "summary": "Place a sale",
        "operationId": "placeSale",
        "parameters": [
          {
            "description": "placed a sale for a product",
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Sale"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Created"
          },
          "400": {
            "description": "Invalid Order"
          }
        }
      }
    },
    "/inventory/sale/return": {
      "post": {
        "produces": [
          "application/json"
        ],
        "tags": [
          "sale"
        ],
        "summary": "Return on sale",
        "operationId": "returnSale",
        "parameters": [
          {
            "description": "placed a return on sale",
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/ReturnSale"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Created"
          },
          "400": {
            "description": "Invalid Order"
          }
        }
      }
    }
  },
  "definitions": {
    "Kardex": {
      "type": "object",
      "title": "Kardex",
      "properties": {
        "id": {
          "type": "string"
        },
        "productId": {
          "type": "string"
        }
      }
    },
    "NewKardex": {
      "type": "object",
      "title": "Kardex",
      "properties": {
        "productId": {
          "type": "string"
        }
      }
    },
    "Purchase": {
      "type": "object",
      "title": "Purchase",
      "required": [
        "productId",
        "quantity",
        "unitPrice"
      ],
      "properties": {
        "productId": {
          "type": "integer",
          "format": "int64"
        },
        "quantity": {
          "type": "integer",
          "format": "int64"
        },
        "unitPrice": {
          "type": "number",
          "format": "double",
          "example": 0.5
        }
      }
    },
    "ReturnPurchase": {
      "type": "object",
      "title": "ReturnPurchase",
      "required": [
        "purchaseId",
        "quantity"
      ],
      "properties": {
        "purchaseId": {
          "type": "integer",
          "format": "int64"
        },
        "quantity": {
          "type": "integer",
          "format": "int64"
        }
      }
    },
    "ReturnSale": {
      "type": "object",
      "title": "ReturnSale",
      "required": [
        "quantity",
        "saleId"
      ],
      "properties": {
        "quantity": {
          "type": "integer",
          "format": "int64"
        },
        "saleId": {
          "type": "integer",
          "format": "int64"
        }
      }
    },
    "Sale": {
      "type": "object",
      "title": "Sale",
      "required": [
        "productId",
        "quantity"
      ],
      "properties": {
        "productId": {
          "type": "integer",
          "format": "int64"
        },
        "quantity": {
          "type": "integer",
          "format": "int64"
        }
      }
    }
  },
  "tags": [
    {
      "description": "Tool that allows you to summarize information about your company's inventory transactions",
      "name": "kardex"
    },
    {
      "description": "Record the purchases of inventory items",
      "name": "purchase"
    },
    {
      "description": "Record the sale of inventory items",
      "name": "sale"
    }
  ]
}`))
}
